name: Publish package

on:
  push:
    tags: ['*']

permissions:
  attestations: write
  id-token: write
  packages: write
  security-events: read

jobs:
  publish-package:
    name: Publish package
    runs-on: ubuntu-latest
    steps:
      - id: checkout-code
        name: Checkout code
        uses: actions/checkout@v6.0.2
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          fetch-depth: 0

      - id: get-alpine-versions
        name: Get Alpine versions
        run: |
          ALPINE_VERSION_PATCH=$(sed -nE "s|^ARG ALPINE_VERSION=(.*)$|\1|p" Containerfile)
          ALPINE_VERSION_MINOR=$(sed -nE "s|^ARG ALPINE_VERSION=(.*)(\.[0-9]+){1}$|\1|p" Containerfile)
          ALPINE_VERSION_MAJOR=$(sed -nE "s|^ARG ALPINE_VERSION=(.*)(\.[0-9]+){2}$|\1|p" Containerfile)
          echo "ALPINE_VERSION_PATCH=${ALPINE_VERSION_PATCH}" >> $GITHUB_OUTPUT
          echo "ALPINE_VERSION_MINOR=${ALPINE_VERSION_MINOR}" >> $GITHUB_OUTPUT
          echo "ALPINE_VERSION_MAJOR=${ALPINE_VERSION_MAJOR}" >> $GITHUB_OUTPUT

      - id: publish-package
        name: Publish package
        uses: nedix/actions/publish-package@main
        with:
          enable_cache: 'true'
          enable_latest_tag: 'false'
          enable_short_sha_tag: 'false'
          enable_version_tag: 'false'
          platforms: linux/amd64,linux/arm64/v8
          registry: ${{ secrets.REGISTRY_DOMAIN || 'ghcr.io' }}
          registry_path: ${{ secrets.REGISTRY_PATH || github.repository }}
          registry_username: ${{ secrets.REGISTRY_USERNAME || github.actor }}
          registry_password: ${{ secrets.REGISTRY_PASSWORD || github.token }}
          tags: |
            ${{ steps.get-alpine-versions.outputs.ALPINE_VERSION_PATCH }}
            ${{ steps.get-alpine-versions.outputs.ALPINE_VERSION_MINOR }}
            ${{ steps.get-alpine-versions.outputs.ALPINE_VERSION_MAJOR }}
